# Generated by Django 4.2.5 on 2023-09-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFileInfo',
            fields=[
                ('csv_file_serial_num', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('x_distance', models.FloatField()),
                ('servo_angle', models.FloatField()),
                ('max_deflection', models.FloatField()),
                ('component_serial_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_serial_num_fk', to='mainapp.component')),
            ],
        ),
    ]
