# Generated by Django 4.2.5 on 2023-09-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_csvfileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFileData',
            fields=[
                ('csv_file_serial_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.csvfileinfo')),
                ('bend_data', models.JSONField()),
            ],
        ),
    ]
