# Generated by Django 4.2.5 on 2023-09-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_csvfiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileinfo',
            name='component_serial_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_serial_num_fk', to='mainapp.component'),
        ),
        migrations.AlterField(
            model_name='csvfileinfo',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='csvfileinfo',
            name='max_deflection',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='csvfileinfo',
            name='servo_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='csvfileinfo',
            name='x_distance',
            field=models.FloatField(null=True),
        ),
    ]
