# Generated by Django 4.2.5 on 2023-09-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_csvfileinfo_component_serial_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfiledata',
            name='csv_file_serial_num',
        ),
        migrations.RemoveField(
            model_name='csvfileinfo',
            name='component_serial_num',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='CsvFileData',
        ),
        migrations.DeleteModel(
            name='CsvFileInfo',
        ),
    ]
