# Generated by Django 4.2.5 on 2023-09-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0005_remove_csvfiledata_csv_file_serial_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_serial_num', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CsvFileInfo',
            fields=[
                ('csv_file_serial_num', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(null=True)),
                ('x_distance', models.FloatField(null=True)),
                ('servo_angle', models.FloatField(null=True)),
                ('max_deflection', models.FloatField(null=True)),
                ('component_serial_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_serial_num_fk', to='mainapp.component')),
            ],
        ),
        migrations.CreateModel(
            name='CsvFileData',
            fields=[
                ('csv_file_serial_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.csvfileinfo')),
                ('bend_data', models.JSONField()),
            ],
        ),
    ]
