# Generated by Django 4.2.5 on 2023-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='csvfiledata',
            name='bend_data',
            field=models.JSONField(null=True),
        ),
    ]
