# Generated by Django 4.2.5 on 2023-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_component_end_time_alter_component_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileinfo',
            name='cycles',
            field=models.IntegerField(null=True),
        ),
    ]
